version: 0.0

os: linux 

files:
  - source: /
    destination: /home/ubuntu/demoNodeProject
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:

  ApplicationStop:
    - location: models/Scripts/stop_server.sh     
      timeout: 300
      runas: root

  BeforeInstall:
    - location: models/Scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
      - location: models/Scripts/after_install.sh
        timeout: 1000
        runas: root

  ApplicationStart:
    - location: models/Scripts/start_server.sh     
      timeout: 300
      runas: root
